LoginTest/LoginTest/Controllers/AlgorithmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHICTDeploymentSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Logic;
using Models;

namespace FHICTDeploymentSystem.Controllers
{
    public class AlgorithmController : Controller
    {
        private readonly AlgorithmLogic _algorithmLogic = new AlgorithmLogic();

        [HttpGet]
        public IActionResult Deploy()
        {
            var viewModel = new AlgorithmViewModel
            {
                Employees = _algorithmLogic.GetAllAssignedTasks(),
                Tasks = _algorithmLogic.GetAllLeftOverTasks()
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult StartAlgorithm()
        {
            _algorithmLogic.StartAlgorithm();

            return RedirectToAction("Deploy");
        }
    }
}

LoginTest/LoginTest/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FHICTDeploymentSystem.Logic;
using FHICTDeploymentSystem.Models;
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using Models;
using Newtonsoft.Json;

namespace FHICTDeploymentSystem.Controllers
{
    public class TeamController : Controller
    {
        private readonly TeamLogic _teamLogic = new TeamLogic();
        private readonly PreferenceLogic _preferenceLogic = new PreferenceLogic();

        [HttpGet]
        public IActionResult ManageTeam()
        {
            User _user = new User
            {
                TeamId = 1
            };

            var userList = _teamLogic.GetTeamUsers(_user);

            return View(userList);
        }

        [HttpPost]
        public IActionResult RemoveUser([FromBody]User _user)
        {
            _teamLogic.RemoveUser(_user);
            return RedirectToAction("ManageTeam");
        }

        [HttpGet]
        public IActionResult ShowTeachers()
        {
            User _user = new User
            {
                Id = 1
            };

            var teacherList = new List<User>();
            var users = _teamLogic.GetAllUserWhitoutTeam(_user);

            foreach (var user in users)
            {
                teacherList.Add(user);
            }
            return View(teacherList);
        }

        [HttpPost]
        public IActionResult AddTeacher([FromBody]User _user)
        {
            var sid = User.Claims.First(c => c.Type.Equals(ClaimTypes.Sid)).Value;
            int.TryParse(sid, out int teamId);
            _user.TeamId = teamId;
            _teamLogic.AddTeacher(_user);
            return RedirectToAction("ManageTeam");
        }
        
        public IActionResult EditUserInTeam(User user)
        {
            var Model = new TeacherModel();
            Model.ID = user.Id;
            Model.Bewkaamheden = _teamLogic.GetTeamMemberCompetences(user);
            Model.Uren = _teamLogic.GetTeamMemberHours(user.Id);
            return View(Model);
        }

        public void SaveHours(int employeeId, int hoursP1, int hoursP2)
        {
            _teamLogic.SaveHours(employeeId, hoursP1, hoursP2);
        }

        public IActionResult EditUserInfo(string jsonding, int employeeId)
        {
            int[] idArray = JsonConvert.DeserializeObject<int[]>(jsonding);
            foreach (int id in idArray)
            {
                _teamLogic.RemoveCompetence(id, employeeId);
            }
            

            return new JsonResult(new { message = "Succes"});
        }

        public IActionResult AddSectionCompetence(int id, int employeeId)
        {
            _teamLogic.AddSectionCompetence(id, employeeId);
            return new JsonResult(new { message = "Succesfully added all tasks in section to competences" });
        }


        public IActionResult AddUnitCompetence(int id, int employeeId)
        {
            _teamLogic.AddUnitCompetence(id, employeeId);
            return new JsonResult(new { message = "Succesfully added all tasks in Unit competences" });
        }


        public IActionResult AddUnitExecCompetence(int id, int employeeId)
        {
            _teamLogic.AddUnitExecCompetence(id, employeeId);
            return new JsonResult(new { message = "Succesfully added all tasks in UnitExec competences" });
        }


        public IActionResult AddTasksCompetence(int id, int employeeId)
        {
            _teamLogic.AddTasksCompetence(id, employeeId);
            return new JsonResult(new { message = "Succesfully added task to competences" });
        }

        public IActionResult AddCompetences(int id)
        {
            User user = new User();
            
            return View(id);
        }

        public IActionResult GetSectionsWhereUserIsNotCompetentFor(int employeeId)
        {
            return Json(_teamLogic.GetSectionsWhereUserIsNotCompetentFor(employeeId));
        }

        public IActionResult GetTermExecsWhereUserIsNotCompetentFor(int employeeId,int id)
        {
            return Json(_teamLogic.GetTermExecsWhereUserIsNotCompetentFor(employeeId,id));
        }

        public IActionResult GetUnitWhereUserIsNotCompetentFor(int employeeId,int id)
        {
            return Json(_teamLogic.GetUnitWhereUserIsNotCompetentFor(employeeId,id));
        }

        public IActionResult GetTasksWhereUserIsNotCompetentFor(int employeeId, int id)
        {
            return Json(_teamLogic.GetTasksWhereUserIsNotCompetentFor(employeeId,id));
        }


        [HttpPost]
        public IActionResult GetAllSections()
        {
            return Json(_preferenceLogic.GetAllSections());
        }

        public IActionResult CreateVacancy(User user)
        {
            var sid = User.Claims.First(c => c.Type.Equals(ClaimTypes.Sid)).Value;
            int.TryParse(sid, out int teamId);
            user.TeamId = teamId;
            _teamLogic.CreateVacancy(user);
            return RedirectToAction("ManageTeam");
        }
    }
}

LoginTest/LoginTest/Controllers/TermExecController.cs
using System.Collections.Generic;
using FHICTDeploymentSystem.Models;
using Logic;
using Microsoft.AspNetCore.Mvc;
using Models;
using Newtonsoft.Json;

namespace FHICTDeploymentSystem.Controllers
{
    public class TermExecController : Controller
    {
        private readonly PreferenceLogic _preferenceLogic = new PreferenceLogic();
        private readonly TermExecLogic _termExecLogic = new TermExecLogic();

        public IActionResult AddUnitTermExec()
        {
            var viewModel = new ManageUnitTermExecViewModel
            {
                Sections = _preferenceLogic.GetAllSections(),
                TermExecs = _termExecLogic.GetAllTermExecs()
            };

            return View(viewModel);
        }

        public IActionResult UnitTermExecSelectorForEdit()
        {
            var viewModel = new ManageUnitTermExecViewModel
            {
                Sections = _preferenceLogic.GetAllSections(),
                TermExecs = _termExecLogic.GetAllTermExecs()
            };

            return View(viewModel);
        }

        public IActionResult EditUnitTermExec(int unitTermExecId)
        {
            var unitTerm = _termExecLogic.GetUnitTermExecFromId(unitTermExecId);

            return View("EditUnitTermExec",unitTerm);
        }

        [HttpPost]
        public void AddUnitTermExec([FromBody] EducationObject termExecToAdd)
        {
            _termExecLogic.AddTermExec(termExecToAdd);
        }
        [HttpPost]
        public void EditTermExec([FromBody] EducationObject termExecToEdit)
        {
            _termExecLogic.EditTermExec(termExecToEdit);
        }
        [HttpPost]
        public void DeleteTermExec([FromBody] EducationObject termExecToDelete)
        {
            _termExecLogic.DeleteTermExec(termExecToDelete);
        }
    }
}

LoginTest/LoginTest/Views/Shared/_Layout.cshtml
@using Models.Enums
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Deployment System</title>

    <!-- CSS  -->
    <link href="~/lib/bootstrap/dist/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <!-- Font Awesome -->
    <link href="~/lib/bootstrap/dist/css/font-awesome.css" rel="stylesheet">
    <!-- Skill Progress Bar -->
    <!-- Owl Carousel -->
    <link href="~/lib/bootstrap/dist/css/owl.carousel.css" rel="stylesheet" />
    <!-- Default Theme CSS File-->
    <link id="switcher" href="~/lib/bootstrap/dist/css/default-theme.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <!-- Main css File -->
    <link href="~/lib/bootstrap/dist/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <!-- Font -->
    @*<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">*@
    <!-- jQuery Library -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Materialize js -->
    <script src="~/js/materialize.min.js"></script>
    <!-- Skill Progress Bar -->
    <script src="~/js/appear.min.js"></script>
    <!-- Owl slider -->
    <script src="~/js/owl.carousel.min.js"></script>
    <link href="~/lib/bootstrap/dist/css/owl.carousel.css" rel="stylesheet" />
    <!-- Mixit slider  -->
    @*<script src="http://cdn.jsdelivr.net/jquery.mixitup/latest/jquery.mixitup.min.js"></script>*@
    <!-- counter -->
    <!-- Custom Js -->
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/buttons.css" rel="stylesheet" />
</head>
<body>

@if (User.Identity.IsAuthenticated)
{
    <header id="header" role="banner">
        <div class="navbar-fixed">
            <nav>
                <div class="container">
                    <div class="nav-wrapper">
                        <a href='@Url.Action("Profile", "Home")' class="brand-logo" style="padding-left: 10px"><img src="~/Images/fontys-logo.png" alt="logo img"></a>
                        <ul class="right hide-on-med-and-down custom-nav menu-scroll">
                            <li><a asp-area="" asp-controller="Home" asp-action="Profile">Profile</a></li>
                            @if (User.IsInRole(Roles.Teacher.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Preference" asp-action="SectionPreference">Preferences</a></li>
                                <li><a asp-area="" asp-controller="Task" asp-action="AssignedEmployeeTasks">My tasks</a></li>
                            }
                            @if (User.IsInRole(Roles.TeamLeader.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Team" asp-action="ManageTeam">Manage team</a></li>
                            }
                            @if (User.IsInRole(Roles.UnitOwner.ToString()) || User.IsInRole(Roles.InstituteMember.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Algorithm" asp-action="Deploy">Deploy</a></li>
                            }
                            @if (User.IsInRole(Roles.UnitOwner.ToString()) || User.IsInRole(Roles.InstituteMember.ToString()))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropButton">Task</a>
                                    <div class="dropdown-content">
                                        <a asp-area="" asp-controller="Task" asp-action="AddTask">Add Task</a>
                                        <a asp-area="" asp-controller="Task" asp-action="TaskSelector">Edit Task</a>
                                        <a asp-area="" asp-controller="Task" asp-action="FixateTaskView">Fixate Task</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropButton">Term Execution</a>
                                    <div class="dropdown-content">
                                        <a asp-area="" asp-controller="TermExec" asp-action="AddUnitTermExec">Add term execution</a>
                                        <a asp-area="" asp-controller="TermExec" asp-action="UnitTermExecSelectorForEdit">Edit term execution</a>
                                    </div>
                                </li>
                            }
                            <input type="button" value="Log Out" onclick="location.href = '@Url.Action("Logout", "Home")'" class="btn btn-primary" />
                        </ul>
                        <ul id="slide-out" class="side-nav menu-scroll">
                            @if (User.IsInRole(Roles.Teacher.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Home" asp-action="Profile">Profile</a></li>
                                <li><a asp-area="" asp-controller="Preference" asp-action="SectionPreference">Preferences</a></li>
                                <li><a asp-area="" asp-controller="Task" asp-action="AssignedEmployeeTasks">My tasks</a></li>
                            }
                            @if (User.IsInRole(Roles.TeamLeader.ToString()))
                            {
                                <li><a asp-area=""  asp-controller="Home" asp-action="Index">Manage Team</a></li>
                            }                       
                            @if (User.IsInRole(Roles.UnitOwner.ToString()) || User.IsInRole(Roles.InstituteMember.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Algorithm" asp-action="Deploy">Deploy</a></li>
                            }
                            @if (User.IsInRole(Roles.UnitOwner.ToString()) || User.IsInRole(Roles.InstituteMember.ToString()))
                            {
                                <li><a asp-area="" asp-controller="Home" asp-action="Movies">Tasks</a></li>
                            }
                        </ul>
                        <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
}
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="col-xl">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted border-top box-shadow">
    <div class="container ">
        &copy; @DateTime.Today.Year - FHICTDeploymentSystem
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>

<style>
    /* Dropdown Button */
    .dropButton {
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
    }

    /* The container <div> - needed to position the dropdown content */
    .dropdown {
        position: relative;
        display: inline-block;
        z-index: 10;
    }

    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        opacity: 1;
        visibility: visible;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #ddd;}

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {display: block;}

    /* Change the background color of the dropdown button when the dropdown content is shown */
    .dropdown:hover .dropbtn {background-color: white;}
</style>